version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./finance_assistant.db
      - SECRET_KEY=asdfghjkl;
      - ALLOWED_ORIGINS=https://typefacefinance-assistant.vercel.app,http://localhost:3000,http://localhost:8000
    volumes:
      - ./:/app