version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./finance_assistant.db
      - SECRET_KEY=your-secret-key
      - ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./:/app