services:
  - type: web
    name: personal-finance-assistant
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./finance_assistant.db
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.vercel.app,http://localhost:3000
    healthCheckPath: /health
    autoDeploy: true